### ISSUE TITLE
Unknown CMake command "_add_library".

### ISSUE THREAD

**Issue by eehlers** [google/brotli#1009]
Configuration of my project fails with:

CMake Error at C:/repos/vcpkg/packages/brotli_x64-windows/share/unofficial-brotli/unofficial-brotli-config.cmake:5 (_add_library):
  Unknown CMake command "_add_library".

What am I doing wrong?

I fixed it temporarily by hacking the above mentioned file and deleting the leading underscore from "_add_library".

**Comment by nimcomputing** [comment]
I believe the issue is with the vcpkg port of Brotli rather than Brotli itself: [https://github.com/microsoft/vcpkg/tree/master/ports/brotli](https://github.com/microsoft/vcpkg/tree/master/ports/brotli)

Seems to be a typo in the file [unofficial-brotli-config.cmake](https://github.com/microsoft/vcpkg/blob/master/ports/brotli/unofficial-brotli-config.cmake)

I'm using a hacky work-around in my projects using Brotli from vcpkg with this in my CMakeLists.txt file:

```
file(READ "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/share/unofficial-brotli/unofficial-brotli-config.cmake" brotli_cmake)
string(REPLACE "_add_library" "add_library" brotli_cmake "${brotli_cmake}")
file(WRITE "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/share/unofficial-brotli/unofficial-brotli-config.cmake" "${brotli_cmake}")
```

**Comment by eustas** [comment]
Thanks for investigating / checking!
