### ISSUE TITLE
Offensive words in dictionary

### ISSUE THREAD

**Issue by rotfllol** [google/brotli#219]
Here are some words that can be seen as offensive. They all exist in the dictionary. Just dump it to a file, and run strings over it, or hexdump -C:

* cockgang
* sonyguysfuckpipe
* puta (this one can be seen as "accidential", as its from two overlapping words "input" + "about")
* Russianlongest
* violenceanywherebenefits

**Comment by jyrkialakuijala** [comment]
I don't see a problem with input|about, Russian|longest and violence|anywhere|benefits  -- this is just a matter of zeroless representation.

sony|guys|fuck|pipe and cock|gang strings may deserve an explanation. Respectively, they consist of four and two separate words in the dictionary. Brotli's dictionary encoding is more compact than in c-strings: no zero bytes are necessary for marking the end of a string. The order in which the words are stored was chosen by an iterative algorithm that was optimizing for compression density. The earlier a word occurs, the less bits are needed to represent it. The words are not together in brotli's dictionary because of co-occurence in the training data, but the placement was driven by population counts, the first position of the word in a file, and by entropy modeling cost of the characters within the word.

The static dictionary data is not available in the brotli program as a human readable document, and does not affect brotli's ability to represent or not represent certain strings.

I will close this issue next week. Please re-open if you need later more information on it.

**Comment by csvan** [comment]
@jyrkialakuijala  - I am pretty sure that the poster is not sincere, and is simply trolling in light of the recent controversy regarding the (now changed) extension for Brotli.

**Comment by jyrkialakuijala** [comment]
@csvan There can be a good reason why he wants to be anonymous.
