### ISSUE TITLE
Recommend a brotli file extension

### ISSUE THREAD

**Issue by c0nk** [google/brotli#288]
Is there any consensus for a brotli file extension? Should this also be .br or .brotli or???

**Comment by broccoli50** [comment]
If someone feels the urgent need to avoid homonyms in their abbreviations they should at least change it to something that doesn't lead to even more homonyms. Making the abbreviation shorter is a terrible idea. For example, `br` stands for bridged networking adapters and also happens to be used for line breaks in HTML.
If you want to avoid ambiguity, at least don't make the problem worse.
If `.bro` is really such a terrible, inhuman word, the least that can be done is changing it to `.brt`.
*Sigh*
___
**Breaking news!** Linux manual page viewer 'man' renamed to 'ma' due to gender issues.

**Comment by jyrkialakuijala** [comment]
There is no brotli file framing format yet, so there shouldn't be a lot of use with files.

**Comment by hansottowirtz** [comment]
`.br` is what https://github.com/google/ngx_brotli uses.
