### ISSUE TITLE
decompressed chunks are incomplete

### ISSUE THREAD

**Issue by mshneer** [google/brotli#325]
I have written a simple test (https://gist.github.com/mshneer/a9b442539917842bc0ef) that breaks HTML into chunks, then compresses, then decompressed. Somehow, there is a difference between chunks that come in and chunks that [come out](https://phabricator.fb.com/P56188426). My understanding that calling _WriteBrotliData(... ,                                    **/* force_flush */ true,** ...)_ should not have this effect.

I was also testing against 0.3.0 release.

Any ideas how to cause the compressor to not buffer things like this?

**Comment by KenjiBaheux** [comment]
Thanks for filing this issue.
cc/ @jyrkialakuijala @eustas

**Comment by eustas** [comment]
Hello.

 After you call "BrotliDecompressBufferStreaming" compressedBytes, most likely, isn't zero. This is because "flush" flag of WriteBrotliData doesn't mean "hard flush". To make a "hard flush" you need to Write empty metablock after flushed data block.

 Sorry for the unclear API documentation. Will fix it soon.

**Comment by eustas** [comment]
s/empty metablock/empty metadata block/

**Comment by eustas** [comment]
Please consider using our new streaming API: `BrotliEncoderCompressStream` with op=`BROTLI_OPERATION_FLUSH` does exactly what is expected.
Sorry for the inconvenience and thank you for your interest to brotli.
