### ISSUE TITLE
Documentation: comparison with other formats

### ISSUE THREAD

**Issue by shevegen** [google/brotli#392]
Hello.

Do you think you could add a short overview between other formats? E. g. speed and compression ratio, as comparison? Nothing big, perhaps just one small markdown table or something.

Feel free to close this issue if this suggestion is considered to be unfit to the project, I was just mostly curious since I did not know brotli yet (sounds swiss german by the way, small bread haha). Thanks!

**Comment by jeroenooms** [comment]
Have you checked https://github.com/google/brotli/blob/master/docs/brotli-comparison-study-2015-09-22.pdf ?

**Comment by nemequ** [comment]
IMHO linking to third-party benchmark(s) would be a better idea, since there is less appearance of bias.  I'm partial to the [Squash Compression Benchmark](https://quixdb.github.io/squash-benchmark/) (or, for a more recent version, [Unstable Squash Compression Benchmark](https://quixdb.github.io/squash-benchmark/unstable/)), but I created them so I'm biased.  Others ([listed in the Squash Benchmark FAQ](https://quixdb.github.io/squash-benchmark/#faq-other-benchmarks)) include:

* [Large Text Compression Benchmark](http://mattmahoney.net/dc/text.html)
* [Squeeze Chart](http://www.squeezechart.com/)
* [Maximum Compression](http://www.maximumcompression.com/)
* [World Compression Challenge](http://heartofcomp.altervista.org/MOC/MOCA.htm)

**Comment by eustas** [comment]
Added section to README.md
