### ISSUE TITLE
Restore parallel encoding/decoding

### ISSUE THREAD

**Issue by thedrow** [google/brotli#484]
It seems that the API for encoding/decoding in parallel was removed for some reason.
Can we please introduce it back?

**Comment by eustas** [comment]
It can be done,... but is there a use case for this. It is easier to make something when there is a clear goal to achieve.

**Comment by thedrow** [comment]
Large payloads can be decompressed more rapidly if you utilize multiple cores.
This is especially true when streaming compressed data through a socket.

Also compressing can be sped up by using multiple cores.

**Comment by eustas** [comment]
Currently there is no way to speedup decoding, unless streams are completely independent -> compressed less efficiently.
We are working on tools that may help create custom dictionaries -> improve compression over multiple chunks.

For multicore compression, I am going to return what was removed, but based on new API (so, not dependent on internal details). But it will be rather a template for multicore compression - it will be a function that compress chunks, but on a single core. To make it multicore, one will be required to add OS dependent multicore wrapper.

**Comment by thedrow** [comment]
Any chance to get this with 1.0?

**Comment by eustas** [comment]
We have some progress in that area. Will start publishing code after v1.0.7 is released.

**Comment by brianbienvenu** [comment]
I'm interested in using this to compress large scientific data files (~200MB) for display via web. I can't precompress, so real-time compression speed is a priority. Single threaded brotli -4 is already improves on pigz's compression ratio for my data, and is fast enough for 11MB/s. With multithreading I could run a higher compression level and get a little more ratio improvement.

**Comment by meisterT** [comment]
Any updates?

**Comment by eustas** [comment]
With new API (`BROTLI_PARAM_STREAM_OFFSET`) it is very easy now =)

Here is a simple test example:
```c++
static void CompressDecompressVerify(
    const string& data, int quality, int lgwin, int num_parts) {
  std::vector<uint8_t> compressed;
  for (size_t i = 0; i < num_parts; ++i) {
    size_t part_start = (i * data.size()) / num_parts;
    size_t part_end = ((i + 1) * data.size()) / num_parts;

    std::vector<uint8_t> original_piece(
        data.begin() + part_start, data.begin() + part_end);
    size_t available_in = original_piece.size();
    const uint8_t* next_in = original_piece.data();

    std::vector<uint8_t> compressed_piece(available_in + 1024, 0);
    size_t available_out = compressed_piece.size();
    uint8_t* next_out = reinterpret_cast<uint8_t*>(&compressed_piece[0]);

    BrotliEncoderState* enc =
        BrotliEncoderCreateInstance(nullptr, nullptr, nullptr);
    EXPECT_NE(nullptr, enc);
    BrotliEncoderSetParameter(enc, BROTLI_PARAM_QUALITY, quality);
    BrotliEncoderSetParameter(enc, BROTLI_PARAM_LGWIN, lgwin);
    BrotliEncoderSetParameter(enc, BROTLI_PARAM_STREAM_OFFSET, part_start);
    auto op =
        (i == num_parts - 1) ? BROTLI_OPERATION_FINISH : BROTLI_OPERATION_FLUSH;
    bool compress_ok = true;
    bool has_more_output = true;
    while (compress_ok && (available_in > 0 || has_more_output)) {
      compress_ok = BrotliEncoderCompressStream(enc, op, &available_in,
        &next_in, &available_out, &next_out, nullptr);
      has_more_output = BrotliEncoderHasMoreOutput(enc);
    }
    BrotliEncoderDestroyInstance(enc);
    EXPECT_EQ(0, available_in);
    EXPECT_FALSE(has_more_output);
    ASSERT_TRUE(compress_ok);
    compressed.insert(compressed.end(),
        compressed_piece.begin(), compressed_piece.end() - available_out);
  }

  string decompressed(data.size() + 1, 0);
  size_t decompressed_size = data.size();
  BrotliDecoderResult result = BrotliDecoderDecompress(compressed.size(),
    reinterpret_cast<const uint8_t*>(compressed.data()), &decompressed_size,
    reinterpret_cast<uint8_t*>(&decompressed[0]));
  ASSERT_EQ(BROTLI_DECODER_RESULT_SUCCESS, result);
  EXPECT_EQ(decompressed_size, data.size());
  int num_mismatches = 0;
  for (int i = 0; i < decompressed_size; ++i) {
    if (decompressed[i] != data[i]) {
      if (num_mismatches < 10) {
        printf("Mismatch at position %d: %d vs %d\n", i,
               decompressed[i], data[i]);
      }
      ++num_mismatches;
    }
  }
  ASSERT_EQ(0, num_mismatches);
}
```

**Comment by jboero** [comment]
I'm not sure why this was closed.  It didn't restore the original parallel feature as requested.  Parallel compression is a simple case of uniform blocks.  The same thing works really well for pigz and parallel gzip.  The workaround I have is to script it, which actually works with good results.  In this example, I'm on a system with 24 logical Xeons (hyperthreaded).  When I split a sample file into 24 chunks and parallel brotli, the difference is night and day with the same compression.

```
[jboero@z640 brotlitest]$ du -sch *
110M    test
110M    total
[jboero@z640 brotlitest]$ split -n 24 test
```
Split 110M test file into 24 even chunks (4.6M).
```
[jboero@z640 brotlitest]$ du -sch *
110M    test
4.6M    xaa
4.6M    xab
4.6M    xac
4.6M    xad
4.6M    xae
4.6M    xaf
4.6M    xag
4.6M    xah
4.6M    xai
4.6M    xaj
4.6M    xak
4.6M    xal
4.6M    xam
4.6M    xan
4.6M    xao
4.6M    xap
4.6M    xaq
4.6M    xar
4.6M    xas
4.6M    xat
4.6M    xau
4.6M    xav
4.6M    xaw
4.6M    xax
219M    total
[jboero@z640 brotlitest]$ time brotli -9 test

real    1m0.282s
user    0m59.769s
sys     0m0.206s
```
Brotli serial with compression level 9 takes almost exactly 1 min.  Now time an alias that compresses all 24 chunks in parallel.
```
[jboero@z640 brotlitest]$ alias parabrotli="ls ??? | parallel brotli -9 {}"
[jboero@z640 brotlitest]$ time parabrotli

real    0m2.912s
user    0m46.376s
sys     0m1.350s
```
2.9sec vs 60sec for the same compression.  Now I would need to tar all of those chunks into one file since I don't think brotli will find the metadata blocks between headers.  It would be nice if brotli could compress parallel with a uniform metablock size just like parallel gzip.
```
[jboero@z640 brotlitest]$ du -sch *.br
24M     test.br
1.5M    xaa.br
736K    xab.br
1.1M    xac.br
1.1M    xad.br
1.2M    xae.br
1.2M    xaf.br
916K    xag.br
1.2M    xah.br
896K    xai.br
828K    xaj.br
1.2M    xak.br
860K    xal.br
1.3M    xam.br
1.2M    xan.br
1.0M    xao.br
988K    xap.br
1.2M    xaq.br
1.1M    xar.br
1.1M    xas.br
1.2M    xat.br
1.8M    xau.br
380K    xav.br
236K    xaw.br
216K    xax.br
47M     total
```

**Comment by mirh** [comment]
Any update?

It sucks that brotli can get LZMA-like compression, blowing it away in extracting speed on a single core.. Only to be surpassed when actually using all those of a modern cpu
(and the zstdmt guys can't be bothered to support large windows)

**Comment by ronny-rentner** [comment]
Any update?

**Comment by thedrow** [comment]
@eustas Can you please reopen this issue?
We'd like to resolve it more concretely as we feel that the example you provided isn't sufficient and the API should be present for parallelism.

**Comment by mirh** [comment]
Another bump...

**Comment by itsTyrion** [comment]
bump

**Comment by WelaurS** [comment]
bump

**Comment by ban1080** [comment]
bump

**Comment by itsTyrion** [comment]
.. this ain't happening. Well, ZSTD it is. zstd has a -T argument for threads

**Comment by sisong** [comment]
I used `BrotliEncoderSetParameter(enc, BROTLI_PARAM_STREAM_OFFSET, part_start);`  for muti-thread parallel encoding;   
It works well when quality<=9;   but:   
* if quality is 10 or 11, then it not work:  decode fail;   why?
* out size is very larger than it compressed by once;   brotli have some API like zlib's `deflateSetDictionary()`?

**Comment by eustas** [comment]
Hi.
 * will investigate what happens on q10, q11, when I have spare cycles.
 * Yes, there is dictionary API (see `BrotliDecoderAttachDictionary`, `BrotliEncoderPrepareDictionary`, `BrotliEncoderDestroyPreparedDictionary`, `BrotliEncoderAttachPreparedDictionary`) and dictionary generator (see `research/dictionary_generator.cc`); you can play with dictionaries from CLI as well (`-D FILE, --dictionary=FILE`)

**Comment by sisong** [comment]
BrotliEncoderAttachPreparedDictionary, it's work;     
( but decoder must used BrotliDecoderAttachDictionary;    )

**Comment by Gonzo2O28** [comment]
any news on this?

**Comment by ccicnce113424** [comment]
https://github.com/dropbox/rust-brotli

**Comment by mirh** [comment]
Insofar as multi-threaded compression may even work, it's only supported if you call the C api
And still no decompression in sight

**Comment by robinwatts** [comment]
I've just written some test code using BROTLI_PARAM_STREAM_OFFSET, and it seems to be working well for me (including for q11).

I do have one question that doesn't seem to be answered anywhere.

Naively, compressing a stream in (say) 4 blocks, you'd fear that each block would have to be completely independent of the last. i.e. over the block boundaries, you'd "lose compression" as blocks couldn't look backwards into the end of the previous block for matches. Then I saw the BROTLI_PARAM_STREAM_OFFSET mechanism and I thought "Ah, clever. You feed the data in for the area before the block you want to compress, and it'll prime the window so that the compression can make use of such matches."

But... no. It looks like that data isn't passed in. So we're left with a choice between maximal compression, or fast compression.

Have I missed a trick here? If so, can someone give me a pointer please? If not, is there scope for an extension to this mode to allow the window to be primed in future?
