### ISSUE TITLE
Is there a way to anyhow use brotli in IE11?

### ISSUE THREAD

**Issue by steric85** [google/brotli#559]

**Comment by eustas** [comment]
Unfortunately, we don't have such information.
Theoretically, if IE provides provides proper API, some kind of extension could be created.
Most probably there is such API, because it is required for Anti-Malware to work.
The problem is - we don't have enough resources to develop "br" extension for IE =(

**Comment by steric85** [comment]
Oh Ohkay. Thanks for informing :)
